Delete strict_host_key_checking from ssh_options if net-ssh does not support it
sorah/hocho pull request #6
Opened 2020-05-31 08:06 UTC by takanabe

## Background

[net-ssh does not accept :strict_host_key_checking as a valid ssh option](https://github.com/net-ssh/net-ssh/blob/3768f1f1a81504909df7b9ee95fdd16f6610096d/lib/net/ssh.rb#L66-L78). As a result, hocho produces an error when ssh config has StrictHostKeyChecking option. This PR removes :strict_host_key_checking from ssh_options when net-ssh does not support it.

<details>
<summary>SSH config</summary>
```
Host host-001.example.com
  User dummy-user
  CheckHostIP no
  StrictHostKeyChecking no
  IdentityFile ~/.ssh/dummy_key
  Port 22
```
</details>

<details>
<summary>Error</summary>
```
bundle exec hocho apply --dry-run host-001.example.com
=> Running on taka-test-001.dev.aws.ckpd.co using mitamae
bundler: failed to load command: hocho (/Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/hocho)
ArgumentError: invalid option(s): strict_host_key_checking
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/net-ssh-6.0.2/lib/net/ssh.rb:221:in `start'
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hocho-0.3.4/lib/hocho/host.rb:202:in `make_ssh_connection'
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hocho-0.3.4/lib/hocho/host.rb:196:in `ssh_connection'
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hocho-0.3.4/lib/hocho/drivers/ssh_base.rb:9:in `ssh'
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hocho-0.3.4/lib/hocho/drivers/mitamae.rb:17:in `run'
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hocho-0.3.4/lib/hocho/runner.rb:22:in `run'
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hocho-0.3.4/lib/hocho/command.rb:85:in `block in apply'
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hocho-0.3.4/lib/hocho/command.rb:77:in `each'
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hocho-0.3.4/lib/hocho/command.rb:77:in `apply'
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/hocho-0.3.4/bin/hocho:4:in `<top (required)>'
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/hocho:23:in `load'
  /Users/takayuki-watanabe/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/hocho:23:in `<top (required)>'
status_code:1

```
</details>

## Changes

* Delete strict_host_key_checking from ssh_options if it's not a valid option.

## Related links

* [valid ssh options for net-ssh](https://github.com/net-ssh/net-ssh/blob/3768f1f1a81504909df7b9ee95fdd16f6610096d/lib/net/ssh.rb#L66-L78)

2020-05-31 08:18 UTC, sorah commented
I was wondering why net-ssh translates ssh_config to an unsupported parameters. https://github.com/net-ssh/net-ssh/blob/3768f1f1a81504909df7b9ee95fdd16f6610096d/lib/net/ssh/config.rb#L214

This might be an upstream bug
https://github.com/net-ssh/net-ssh/issues/764

However, we need to support `host_key_verify` option at Hocho `Host#openssh_config` to properly support `StrictHostKeyVerification` option... https://github.com/sorah/hocho/blob/0a4a1e0c8f40f539e684810b42daf2ec7bac24a9/lib/hocho/host.rb#L104

2020-05-31 12:37 UTC, sorah requested changes
flagging request changes https://github.com/sorah/hocho/pull/6#issuecomment-636438799

- We need to support `host_key_verify` in `Host#openssh_config`
- `Net::SSH::Config` should not emit `strict_host_key_validation` as it's not supported, this should be an upstream bug - correct me if I'm wrong

2020-06-01 13:09 UTC, takanabe commented
I pushed a commit to support verify_host_key option by hocho https://github.com/sorah/hocho/pull/6/commits/a8f47667776fabeba0dee9b5526c717d2a3bee74

>Net::SSH::Config should not emit strict_host_key_validation as it's not supported, this should be an upstream bug - correct me if I'm wrong

Agree. This is a bug of net-ssh and we should not read a value of strict_host_key_checking from ssh configs if it does not accept as a valid option.  I'll leave comments on the net-ssh repository. The reason I pushed https://github.com/sorah/hocho/pull/6/commits/c786b45be7054c194ca5a76d8e1d9f9f6ebac5ca here is just for workaround against the upstream problem.

2020-06-01 14:45 UTC, takanabe commented
The bug net-ssh should be fixed with https://github.com/net-ssh/net-ssh/pull/765 📝

2020-06-01 15:02 UTC, sorah approved these changes

2020-06-01 15:02 UTC, merged